services:
  - type: web
    name: clever-roadmap-bot
    env: python
    region: frankfurt
    plan: starter
    numInstances: 1

    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /

    envVars:
      - key: PYTHONPATH
        value: app

      - key: BOT_TOKEN
        sync: false

      - key: GOOGLE_API_URL
        sync: false

      - key: CACHE_TTL
        value: "60"
